version: "2"

linters:
  default: all
  disable:
    - exhaustruct
    - depguard
    - wrapcheck
    - tagalign
    - forbidigo
    - perfsprint
    - gochecknoglobals
    - wsl  # deprecated
    - revive  # too noisy
    # Legacy code suppressions:
    - errcheck
    - modernize
    - noinlineerr
    - staticcheck
    - wsl_v5

issues:
  exclude-rules:
    - path: (.+)_test.go
      linters:
        - paralleltest
        - funlen
        - testpackage
