linters:
  enable-all: true
  disable:
  # Dont care:
  - exhaustruct
  - depguard
  # Deprecated:
  - exportloopref
  - execinquery
  - gomnd
  - perfsprint
  - gochecknoglobals
  # Extra:
  - tagalign

issues:
  exclude-rules:
    - path: (.+)_test.go
      linters:
        - paralleltest
        - funlen
        - testpackage